### ISSUE TITLE
Waveshare 7.8in HAT support?

### ISSUE THREAD

**Issue by grooverkm** [robweber/omni-epd#47]
Don’t know if this is the right place to ask, but is there any chance to support the waveshare 7.8in HAT screen at all?

https://www.waveshare.com/wiki/7.8inch_e-Paper_HAT

I would love to replace my Rasp Pi 4b / 7in5_V2 screen (which works perfectly) with this higher res screen that I bought months ago but I haven’t got anywhere with waveshare directly.  They have no plans to support their own screen in the python library -

<waveshare support> “I'm sorry that we don't have a plan to release a python driver for the library, since the speed of the parallel port screen is too slow if you use python to refresh it.”

I don’t understand the answer (I’m a beginner following instructions), but hoped someone here could help.

**Comment by robweber** [comment]
I looked around on the Waveshare page for that item. The primary focus of this project is to abstract devices that have existing Python drivers into an easy to use library that works regardless of the actual device implementation. If Waveshare won't provide a Python interface there isn't a lot to work with on that front. 

Their explanation seems to have something to do with the speed of Python vs compiled code (C?) on that particular device. Without more info on the low level hardware I'm not sure why that's the case but I'll take their explanation at face value that it is. Python could send the same commands that the compiled library does but you'd have to re-create it from scratch and would need a working piece of hardware to do so. Sorry can't help more.
