### ISSUE TITLE
Inky Impression library doesn't work

### ISSUE THREAD

**Issue by Camper71** [robweber/omni-epd#54]
I have followed the Pimoroni instructions w/ latest version (1.3.1) and installed Omni-epd with my Inky Impression color 5.7" display on raspberry pi 3 A+ and 4 B+, however the command omni-epd-test -e inky.impression does nothing. It doesn't update the display or output anything. However - if I run omni-end-test -e waveshare_epd.epd5in83 the screen will update.

more curious, the examples provided by Pimoroni (logo.py, stripes.py etc) will not work, but if I run omni-end-test -e waveshare_epd.epd5in83 immediately after, the screen will refresh with the aforementioned Pimoroni example image. Running it a second time will result in the screen drawing the squares as designed.

**Comment by robweber** [comment]
That all sounds really crazy! At a very low level it makes each EPD driver is just sending commands to the board, so perhaps there is some overlap in the low level IO; but the fact that a completely different vendor's implementation is working on the Inky is some bizarre behavior. 

One telling thing is that the Pimoroni examples aren't working. These are default from the manufacturer so those not working as designed is kind of a red flag. I'm curious why you tried the waveshare driver, and why that particular one? 

@missionfloyd - you had originally verified the Inky Impression code so I'm guessing you have one? Any troubleshooting steps you can think of?

**Comment by Camper71** [comment]
I tried SlowMovie and changed the preference, and it didn't work. I then tried the helloworld demo that came with SlowMovie - and for the first time something happened - a Pimoroni demo I had submitted earlier (or the previous day) showed up on the screen. I looked at the code and it imported the epd7in5_v2 driver. I tried drivers in your omni-epd call (starting with inky.impression - which did nothing) until one worked regularly (5in83) in your draw rectangles test. Now I can regularly reproduce the following - 1. Submitting Pimoroni script (nothing happens but script thinks it succeeds' 2. run omni-end-test -e waveshare_epd.epd5in83 and the image from step 1 appears. Odd, right? I was hoping your inky.impression driver would just work..

**Comment by Camper71** [comment]
here is a video (zipped). if you look at the screen before you play the video you can see identify.py telling me my display properly. then I run stripes. nothing happens..a previous logo image remains on screen. Video starts with me run omni-epd-test with the waveshare driver and you can see the inky screen - and  it draws stripes based on the stripes.py script. 
[IMG_2473.mov.zip](https://github.com/robweber/omni-epd/files/7919487/IMG_2473.mov.zip)

**Comment by Camper71** [comment]
curious - as I'm not a developer/engineer - is there some command that is missing from the inky.impression driver that exists and is triggered at the start of the waveshare epd7in5_v2 driver..that could result in activating whatever was in the 'buffer' (for lack of a better term)

**Comment by missionfloyd** [comment]
I just installed the latest inky and omni-epd versions, and `omni-epd-test -e inky.impression` seems to work here.

As for the pimoroni examples, did you enable i2c? It's needed for autodetection to work.

There's a [PR](https://github.com/pimoroni/inky/pull/141) regarding a bug in inky impression autodetection over on pimoroni's repo: https://github.com/pimoroni/inky/pull/141. Mine works without it, but yours may be a newer revision or something. You can also manually specify a display with the `--type impressions` argument

**Comment by Camper71** [comment]
Yes, I2C is enabled. I went through a clean install with video per
Pimoroni support and they sent me a new panel- I’ll update you if it
works…



On February 26, 2022, Rob ***@***.***> wrote:
> I just installed the latest inky and omni-epd versions, and omni-epd-
> test -e inky.impression seems to work here.
>
> As for the pimoroni examples, did you enable i2c? It's needed for
> autodetection to work.
>
> There's a PR <https://github.com/pimoroni/inky/pull/141> regarding a
> bug in inky impression autodetection over on pimoroni's repo:
> pimoroni/inky#141 <https://github.com/pimoroni/inky/pull/141>. Mine
> works without it, but yours may be a newer revision or something. You
> can also manually specify a display with the --type impressions
> argument
>

—
Reply to this email directly, view it on GitHub
<https://github.com/robweber/omni-epd/issues/54#issuecomment-
1053120516>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AXNGIF2DXA2XXF3UOLHQTULU5GUA7ANCNFSM5MRDHTAA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by robweber** [comment]
Thanks for the update. Please follow-up, perhaps it's just a hardware issue after all.

**Comment by Camper71** [comment]
I finally tested the new Inky and it worked on the first try with the
same install I was struggling with..so it was definitely a hardware
issue. 

thanks again!

cb

On February 27, 2022, Rob ***@***.***> wrote:
> Thanks for the update. Please follow-up, perhaps it's just a hardware
> issue after all.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/robweber/omni-epd/issues/54#issuecomment-
1053600883>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AXNGIF4CCDMHEOAW2JJNRF3U5JDTVANCNFSM5MRDHTAA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were assigned.Message ID:
***@***.***>

**Comment by robweber** [comment]
That's great news - although not super awesome you had to get a whole new piece of hardware. Glad it's working.
