### ISSUE TITLE
Black vs BW

### ISSUE THREAD

**Issue by robweber** [robweber/omni-epd#61]
I noticed when looking through things that some devices use `bw` as they default mode identifier while others use `black`. It's more of a semantic difference but sticking with a single identifier across all types would be more consistent. There are also areas in the parent `virtualepd.py` class where it checks specifically for `bw` as a string before applying certain functions. 

Might be worth the effort of defining some constants for comparisons as well as consistency.

**Comment by donbing** [comment]
if someone is using `mode=bw` in their config, would this be a breaking change?

I agree that it'd be very nice to fix it.

**Comment by robweber** [comment]
@missionfloyd  - thanks for the PR. 

I added a [quick check](https://github.com/robweber/omni-epd/commit/feb6f3dcd93261502697434b6518415a1c79cab8) in the parent `VirtualEPD` class to check if `black` is given as a mode. If it is a warning will be shown and it will be set to `bw`. This will give anyone a heads up and time to correct their config files.
