### ISSUE TITLE
Mock Display Palette with Dithering

### ISSUE THREAD

**Issue by robweber** [robweber/omni-epd#69]
This doesn't impact usability in a meaningful way but it is a shortcoming. When using the `omni_epd.mock` display in `color` mode the value of the `palette_filter` attribute returns the colors for black and white but no other colors. 

The main effect this has is if you also try and apply a dither effect to the image when using the mock display. The dithering process [expects this attribute to exist](https://github.com/robweber/omni-epd/blob/main/src/omni_epd/virtualepd.py#L192) and have correct values. When testing this on a color image, applying a dither always results in a black and white image as that is the returned palette. 

Since the mock display is really more of a testing tool it isn't a meaningful usability issue but will not yield correct results in it's current form. 

### Issues with a fix 

A simple fix for this wasn't evident at first glance. The dithering code is triggered when `display()` is called within the parent `VirtualEPD` class prior to the display implementation method `_display()` being called. As a result the effect is already applied before the specific device class has access to the Image. Because this is a parent class function it's not easy to code around this by simply importing the palette of the `Image` object. There are other displays that use `color` as their mode that do set a proper palette correctly from the device driver. 

### Workarounds

Not really a workaround but if no fix can be found I think it would be ok to simply document this as a shortcoming and leave it as is. It's not really a show stopper as it doesn't effect actual devices.

**Comment by missionfloyd** [comment]
Just installed 736f0e7fa3d50926f48b2fea19996208178b6cea to check this. Seems to work here.
![mock_output](https://user-images.githubusercontent.com/4073789/157393171-d31e8fbb-3938-4181-bb01-756dd7da45f3.png)
```ini
[EPD]
type=omni_epd.mock
mode=color
# DESATURATED_PALETTE from inky impression lib
palette_filter=[[0, 0, 0], [255, 255, 255], [0, 255, 0], [0, 0, 255], [255, 0, 0], [255, 255, 0], [255, 140, 0], [255, 255, 255]]
width=800
height=480

[Display]
dither=floyd-steinberg
```
I've also been working on [improving the dithering](https://github.com/missionfloyd/omni-epd/tree/didder).

**Comment by missionfloyd** [comment]
I tried to see if PIL could quantize it to a specific number of colors. `quantize()` sort of worked, but wouldn't dither it, and the colors looked pretty bad.

Imagemagick can do it. 
```python
#!/usr/bin/python3

import subprocess, io, sys
from PIL import Image

colors = 16

image = Image.open("omni-epd/examples/PIA03519_small.jpg")
buf = io.BytesIO()
image.save(buf, "PNG")

proc = subprocess.Popen(["convert", "-", "-dither", "None", "-colors", str(colors), "-"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
out, err = proc.communicate(input=buf.getvalue())
buf.close()

# out can be used as the palette image for PIL
"""
buf = io.BytesIO(out)
image = Image.open(buf).copy()
buf.close()
"""
# or it can be passed to this to output a list of colors
proc = subprocess.Popen(["convert", "-", "-unique-colors", "txt:-"], stdin=subprocess.PIPE, stdout=subprocess.PIPE)
out, err = proc.communicate(input=out)
```
```
# ImageMagick pixel enumeration: 16,1,255,srgb
0,0: (1,1,4)  #010104  srgb(1,1,4)
1,0: (12,8,17)  #0C0811  srgb(12,8,17)
2,0: (34,14,41)  #220E29  srgb(34,14,41)
3,0: (82,23,50)  #521732  srgb(82,23,50)
4,0: (41,27,84)  #291B54  srgb(41,27,84)
5,0: (89,39,88)  #592758  srgb(89,39,88)
6,0: (73,80,65)  #495041  srgb(73,80,65)
7,0: (99,85,102)  #635566  srgb(99,85,102)
8,0: (167,57,92)  #A7395C  srgb(167,57,92)
9,0: (155,91,105)  #9B5B69  srgb(155,91,105)
10,0: (205,152,108)  #CD986C  srgb(205,152,108)
11,0: (75,65,150)  #4B4196  srgb(75,65,150)
12,0: (98,89,152)  #625998  srgb(98,89,152)
13,0: (166,100,148)  #A66494  srgb(166,100,148)
14,0: (102,155,159)  #669B9F  srgb(102,155,159)
15,0: (204,173,164)  #CCADA4  srgb(204,173,164)
```

**Comment by robweber** [comment]
Added a hardcoded palette based on the list of standard [web safe colors](https://en.wikipedia.org/wiki/Web_colors#Web-safe_colors). These are an accepted 216 color list that should yield a decent looking image. I think this is reasonable for a virtual testing class and will allow functions, like dithering, to work in a test environment without resulting a black and white image.
