### ISSUE TITLE
Waveshare 3 Ink displays

### ISSUE THREAD

**Issue by robweber** [robweber/omni-epd#7]
Per @missionfloyd the library currently won't handle Waveshare's 3 ink displays as they require 2 `Image` objects passed to the `display()` function in the Waveshare library. 

https://github.com/TomWhitwell/SlowMovie/pull/64#issuecomment-824383451

**Comment by robweber** [comment]
After examining the waveshare code a bit more passing in `None` for the second image to display b/w only seems like a fairly simple option. Probably best way to handle these for now. 

If utilizing the second color is something to support the following steps could probably be used: 

1. perform a `P` mode transformation on the image to get it down to 3 colors, can use existing image enhancements for this as part of [_applyConfig()](https://github.com/robweber/omni-epd/blob/main/src/omni_epd/virtualepd.py#L55)
2. Use `getcolors()` from the [Pillow library](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.getcolors) to identify what 3 colors were used in the transform
3. Within the `_display()` method do a second palette filter to separate colors 1+2 and colors 1+3 into separate images. This would correspond to the _black image_ and _red image_ vars the EPD expects. 
4. pass these to `display(im1,im2)` in the waveshare lib

Without a display to test this on it's hard to say if this would be successful.

**Comment by robweber** [comment]
This got way more complicated than I expected - apparently there is a lot of variation in the different waveshare classes. Oddly a lot of places where there doesn't even need to be; things like function names being different for no reason or basically the same arg being different between devices. 

In any case #8 is my attempt at consolidating it all into something workable. @missionfloyd please take a look and see if this helps with the issues you found. Definitely more work to be done here in terms of allowing access to advanced params but this gets the basics knocked out.

**Comment by missionfloyd** [comment]
I don't have a 3 color display either, so I can't test it.

**Comment by robweber** [comment]
Thanks for the feedback, I can make the adjustments tomorrow. I found some example [digging on Github](https://github.com/txoof/epdlib/blob/master/epdlib/Screen.py#L355) of passing the blank image to the 3 color display drivers so I'm assuming that's what's working for people when they don't need the third color. I'm hesitant to implement anything more substantial without hardware to test. I think this will get the bulk of the waveshare devices working, at least for B/W images like we're targeting.

**Comment by missionfloyd** [comment]
Some of the waveshare drivers (the ones that people have [optimized](https://github.com/waveshare/e-Paper/blob/af9694c602fb24d776cd0f0b3e073a477294e3d8/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd7in5_V2.py#L150)) use the array of zeroes to clear the screen. I've been messing with pillow, with okay results.
![out2](https://user-images.githubusercontent.com/4073789/115784594-91f52880-a37b-11eb-929f-f4095a1ee730.png)
Then what [pimoroni](https://github.com/pimoroni/inky/blob/75f12b415ad1ae42ac3be92b33f83f51519f5da3/library/inky/inky_ssd1608.py#L229-L249) does is use numpy to split the image into the black and red layers.

**Comment by robweber** [comment]
That's awesome. I'm going to leave this open but merge in #8 soon. That will give us b/w and fix issues with most of the waveshare drivers. Then we can layer this in to add the third color for displays that support it via another PR. 

Really cool work on this.

**Comment by robweber** [comment]
#12 is merged - should close this out.
