### ISSUE TITLE
Not working with Waveshare 2.13inch Touch e-Paper HAT

### ISSUE THREAD

**Issue by redphx** [robweber/omni-epd#74]
![](https://www.waveshare.com/img/devkit/LCD/2.13inch-Touch-e-Paper-HAT-with-case/2.13inch-Touch-e-Paper-HAT-with-case-details-1.jpg)
- [Product Info](https://www.waveshare.com/2.13inch-touch-e-paper-hat-with-case.htm)
- [Wiki Page](https://www.waveshare.com/wiki/2.13inch_Touch_e-Paper_HAT)
- [Demo](https://github.com/waveshare/Touch_e-Paper_HAT/blob/main/python/examples/TP2in13_test.py)
- [EPD Lib](https://github.com/waveshare/Touch_e-Paper_HAT/blob/main/python/lib/TP_lib/epd2in13_V2.py)

The demo from Waveshare works without modification. When I run `omni-epd-test -e omni_epd.mock`, there was no errors but the screen was blank/empty.

**Comment by redphx** [comment]
Tested with `waveshare_epd.epd2in13_V2` and it worked! `sleep()` and `clear()` features work too. Thank you.

**Comment by robweber** [comment]
Awesome, glad that got it all working.
