### ISSUE TITLE
Couldn't find waveshare_epd.epd5in65f

### ISSUE THREAD

**Issue by jezs00** [robweber/omni-epd#80]
Thanks for your development of this tool. I've implemented this in a project I'm working on. Previously was working with "waveshare_epd.epd7in5_V2", however I have tried to implement using a "waveshare_epd.epd5in65f". Official screen tests from waveshare work.

Receiving error on run for 'waveshare_epd.epd5in65f'
INFO:root:Couldn't find waveshare_epd.epd5in65f

When running displayfactory.list_supported_displays() I get a 'waveshare_epd.epd5in64f' in the list, which does not appear to be a valid name for a waveshare driver/product. When trying to run for waveshare_epd.epd5in64f as a test:
"waveshare_epd.epd5in64f not found, refer to install instructions"

Tried reinstalling waveshare package, no dice. Have tried to find where this error is occurring but I've not been able to dig too far into this code. Logging issue just in case it actually is an issue. As far as I can tell there may be a minor spelling error but can't find the text in the drivers or the code of this repo, really scratching my head about this one.

**Comment by jezs00** [comment]
Fixed it on my end I think. I must have an old or broken version, found the error in:
home/pi/.local/lib/python3.7/site-packages/omni_epd/displays/waveshare_display.py:    deviceList = ["epd5in64f", "epd4in01f"]

I removed, uninstalled and reinstalled and it works. Apologies.

**Comment by robweber** [comment]
Glad you got it all fixed up. Guessing the old version thing was the culprit. Looking back at commits this was caught and fixed a while back: https://github.com/robweber/omni-epd/commit/3b50d54f8235c2b26f5fa81884c5f02def849344
