### ISSUE TITLE
Streaking on SlowMovie maybe epd related? 

### ISSUE THREAD

**Issue by TomWhitwell** [robweber/omni-epd#82]
Hi, getting odd (new) streaking on my original Slowmovie player: 
https://github.com/TomWhitwell/SlowMovie/issues/134#issuecomment-1378458314 
Wonder if it's something to do with omni-epd? 

Using: epd = waveshare_epd.epd7in5_V2

**Comment by robweber** [comment]
Going to close this out to get all the comments about this into https://github.com/TomWhitwell/SlowMovie/issues/143
