### ISSUE TITLE
Thank you. Possible update to README.

### ISSUE THREAD

**Issue by jezs00** [robweber/omni-epd#83]
Hello. Not sure of etiquette on GitHub, I'm pretty new to the whole site and contributing to things, and have mostly just been learning on my own best practises, so sorry if posting this issue here is inappropriate. There's not really any other way to send a message to anyone I guess. Firstly I just wanted to send a thanks to Tom and Rob for your work on SlowMovie and omni-epd. I've learned a lot from both of your code and it formed the basis of my own little project. I used omni-epd in my code which was incredibly useful as a wrapper for EPDs and I also used it to learn a bit about how tests and projects should be structured, and I used the very cool install.sh from SlowMovie for my own bash install script.

My project is here: https://github.com/jezs00/pycasso

I've added acknowledgements in the README and I plan to do a little writeup shortly like the SlowMovie article and call out your influence there as well.

Just a short note in case anything I've done, code I've used or reference, or acknowledgements aren't appropriate. Please let me know.

You can put this project in the README if you like as a project implementing omni-epd.

Feel free to just close this issue once read.

**Comment by robweber** [comment]
Thanks for the note regarding your project. I'm sure GitHub is trying to cut down on unwanted messages to people by not having a better direct message channel but it's annoying at times. I've resorted to making issues when no other way presents itself as well. 

I'm glad you found this library and code examples useful. I took a quick look through your repo and that EPD project with the AI art looks pretty cool. I'll have to read through the instructions in more detail and try it out for myself. Displaying movie frames is fun but this would be interesting to try this as well. 

I'll definitely add your project to the README here. I'll keep this issue open as a reminder until I get it done. SlowMovie is MIT licensed and this project is GPLv3 so no worries on the references or acknowledgements.
