### ISSUE TITLE
Waveshare 1872×1404 7.8inch display only supports "bw" mode, should support "gray4"

### ISSUE THREAD

**Issue by jantielens** [robweber/omni-epd#88]
First of all: amazing work! <3

I have a [Waveshare 1872×1404 7.8inch](https://www.waveshare.com/7.8inch-e-paper-hat.htm) display. It's working with `omni-epd` but it only seems to support the `bw` mode, although it's a display that can do 16 grayscales so it should support the `gray4` mode as well.

The list of list of [implemented displays](https://github.com/robweber/omni-epd#displays-implemented) only lists `bw` as a mode, just like all other displays using the `waveshare_epd.it8951` driver. I have verified in code, that also the the `modes_available` function only returns `bw`.

I'll be looking through the code to see if I can find where to adjust this. But if you have any pointers in the meanwhile, or a fix, that would be super cool.

Thanks!

**Comment by robweber** [comment]
Thanks for pointing this out. Looking through the Waveshare link it seems all the IT8951 devices support 16 shade grayscale. Looking at the IT8951 library I couldn't find any special way to handle this so I'm guessing the display driver must take care of it on it's own. 

I [created a branch](https://github.com/robweber/omni-epd/tree/it8951_greyscale) and added support for a `gray16` mode type. If you're able to clone and build this branch for testing that would be great. Hoping this is an easy case of just exposing the functionality.

**Comment by jantielens** [comment]
Super, I'll give it a try and report back. Thanks 🙏
