### ISSUE TITLE
Driver for Inky impression 7.3

### ISSUE THREAD

**Issue by MivilleSchester** [robweber/omni-epd#96]
The file "display_inky.py" don't include the driver for inky impression 7.3. The Pimoroni file for the Inky 7.3 is "inky_ac073tc1a.py"

**Comment by robweber** [comment]
It looks like there are different files for the various versions of the Inky 7.3 display that have different resolutions. The driver being loaded `inky_uc8159.py` is the one that was originally available and tested. Taking a look at the [auto class](https://github.com/pimoroni/inky/blob/main/library/inky/auto.py#L35) from the inky library it looks like later revisions of this device use the other driver you indicated. 

Have you tried using `inky.auto` to auto detect the driver? This uses Inky's built in detection and tries to load the file directly based on your version.

**Comment by robweber** [comment]
Great. I also added some wording to the README to make it a bit more clear this is the preferred driver to use.
